language: ruby
rvm:
  - 2.1.2
branches:
  only:
    - master
before_script:
  - mysql -e 'create database ecd;'
  - mysql -e 'create database efd_contribuicoes;'
  - mysql -e 'create database efd_icms_ipi;'
script: ruby travis_script.rb